### PR TITLE
Change bosh deployment events to use events emitted from bosh

### PR DESCRIPTION
**Pull request by DennisDenuto**
Instead of from concourse or other sources.

See: https://github.com/cloudfoundry/bosh/blob/master/bosh-director/lib/bosh/director/deployment_plan/notifier.rb

[#116342619]

Signed-off-by: Dennis Leon dleon@pivotal.io

### CODE REVIEW

**Comment by emalm** [comment]
Thanks, @DennisDenuto! Prioritizing for evaluation.

Best,
Eric

**Comment by DennisDenuto** [comment]
The change to a single line with many OR statements reflects the actual behavior of datadog when evaluating the events (i.e. datadog will truncate and discard every event but the first element in the `events` array so the previous json never actually worked properly).

**Comment by emalm** [comment]
Thanks, @DennisDenuto. I don't see `OR`s in some of the last lines added in the diff. I know complexity in ERb is a slippery slope, but would it make sense for a preamble to DRY up the events JSON boilerplate into a single template-local variable that can be included in each graph?

Best,
Eric

**Comment by DennisDenuto** [comment]
Thanks for the feedback @ematpl 
We have declared a template-local variable that contains the event query used in each graph.

**Pull request merged**
